[

{"@id": "http://docs.oasis-open.org/tac/ns/stix-cve#CVE-2020-36325", "@type": ["http://www.w3.org/2002/07/owl#NamedIndividual", "http://docs.oasis-open.org/cti/ns/stix#Vulnerability"], "http://docs.oasis-open.org/cti/ns/stix/core#description": [{"@value": "An issue was discovered in Jansson through 2.13.1. Due to a parsing error in json_loads, there's an out-of-bounds read-access bug."}], "http://docs.oasis-open.org/cti/ns/stix/core#modified": [{"@value": "2021-04-27T00:32:24.108151Z"}], "http://docs.oasis-open.org/cti/ns/stix/core#created": [{"@value": "2021-04-27T00:32:24.108151Z"}], "http://docs.oasis-open.org/cti/ns/stix/core#spec_version": [{"@value": "2.1"}], "http://docs.oasis-open.org/cti/ns/stix/core#id": [{"@value": "vulnerability--621a2526-3f31-4241-a931-5c939e7a9998"}], "http://docs.oasis-open.org/cti/ns/stix/core#name": [{"@value": "CVE-2020-36325"}], "http://docs.oasis-open.org/cti/ns/stix/core#created_by_ref": [{"@id": "http://docs.oasis-open.org/tac/ns/stix-cve#identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a"}], "http://docs.oasis-open.org/cti/ns/stix/marking#object_marking_refs": [{"@id": "http://docs.oasis-open.org/tac/ns/stix-cve#marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"}]}

]